### PR TITLE
simpod GrafanaJsonDatasource breaking change 'data' to 'payload'

### PR DESCRIPTION
**Pull request by SirkoVZ**
there was a breaking change on GrafanaJsonDatasource
https://github.com/simPod/GrafanaJsonDatasource/releasesversion 0.3.0
I hope, my changes are enough, however, seems to work now

### CODE REVIEW

**Comment by blissi** [comment]
I can also confirm that this works.

**Comment by andig** [comment]
Thanks for the hint

**Comment by blissi** [comment]
My apologies, I was too fast:
It does work when you use a query that uses grouping for example.
But for other queries without a JSON payload it doesn't work:

> 2022/11/07 15:04:56 POST /query (0ms)
> 2022/11/07 15:04:56 json decode failed: json: cannot unmarshal string into Go struct field Target.targets.payload of type grafana.TargetData

**Comment by blissi** [comment]
The reason is that the payload-field comes as an empty string.

**Pull request merged**
